apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a21-app
  namespace: tools
spec:
  project: a21-project
  source:
    repoURL: https://github.com/keenbytes/apps-of-apps-example
    targetRevision: HEAD
    path: app/a21
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated: {}
