apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: c11-set
  namespace: tools
spec:
  generators:
    - git:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        revision: HEAD
        directories:
          - path: app/c111
          - path: app/c112
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: tools
      syncPolicy:
        automated: {}
