apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sub-set-b
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        revision: HEAD
        directories:
          - path: apps/second-level/b1
          - path: apps/second-level/b2
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}
