apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-set-a
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        revision: HEAD
        directories:
          - path: apps/first-level/a
  template:
    metadata:
      name: '{{path.basename}}-as'
    spec:
      project: default
      source:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated: {}
